Algoritmo "cronometro"
// Disciplina   : [Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : Temporizador que vai de 59 minutos e 59 segundos até 0.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 04/04/2024
Var
   contadoramin,contadoraseg:inteiro
Inicio
   para contadoramin de 59 ate 0 passo -1 faca
      para contadoraseg de 59 ate 0 passo -1 faca
         Escreval(contadoramin,":",contadoraseg)
         timer 333
      fimpara
   fimpara
Fimalgoritmo