Algoritmo "Celsius para Fahreinheit"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar a temperatura em Celsius e converter para Fahreinheit
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
tempcel:real
Inicio
Escreval("Digite a temperatura em graus Celsius: ")
Leia(tempcel)
Escreval("A temperatura em graus Gahreinheit é de:", (9*tempcel+160)/5)
Fimalgoritmo