Algoritmo "somadosquadrados"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa lê três valores diferentes e realiza a soma dos quadrados de cada um deles.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
A,B,C:real
Inicio
Escreval("Digite o primeiro valor: ")
Leia(A)
Escreval("Digite o segundo valor: ")
Leia(B)
Escreval("Digite o terceiro valor: ")
Leia(C)
Escreval("A soma dos quadrados dos valores é:",A^2+B^2+C^2)
Fimalgoritmo