Algoritmo "PropriedadeDistributiva"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Ler 4 valores inteiros e realizar a adição e multiplicação de todos com base na propriedade distributiva.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
A,B,C,D:inteiro
Inicio
Escreval("Escreva o valor de A: ")
Leia(A)
Escreval("Escreva o valor de B: ")
Leia(B)
Escreval("Escreva o valor de C: ")
Leia(C)
Escreval("Escreva o valor de D: ")
Leia(D)
Escreval("A soma de A com B é:", A+B)
Escreval("A soma de A com C é:", A+C)
Escreval("A soma de A com D é:", A+D)
Escreval("A soma de B com C é:", B+C)
Escreval("A soma de B com D é:", B+D)
Escreval("A soma de C com D é:", C+D)
Escreval("A multiplicação de A com B é:", A*B)
Escreval("A multiplicação de A com C é:", A*C)
Escreval("A multiplicação de A com D é:", A*D)
Escreval("A multiplicação de B com C é:", B*C)
Escreval("A multiplicação de B com D é:", B*D)
Escreval("A multiplicação de C com D é:", C*D)
Fimalgoritmo