Algoritmo "Invertendovalores"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa lê dois valores e atribui as variaveis A e B, depois, inverte os valores.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
A,B,C:real
Inicio
Escreval("Escreva o primeiro valor: ")
Leia(A)
Escreval("Escreva o segundo valor: ")
Leia(B)
C<-A
A<-B
B<-C
Escreval("O primeiro valor virou:",A)
Escreval("O segundo valor virou:",B)
Fimalgoritmo