Algoritmo "volumecaixaretangular"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Ler a altura, largura e comprimento de uma caixa retangular, calcular e exibir seu volume.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
altura,largura,comprimento:real
Inicio
Escreval("Escreva a altura da caixa: ")
Leia(altura)
Escreval("Escreva a largura da caixa(na mesma unidade de medida da altura): ")
Leia(largura)
Escreval("Escreva o comprimento da caixa(na mesma unidade de medida da altura): ")
Leia(comprimento)
Escreval("O volume da caixa retângular é de(1cm³ = 1ml):", altura*largura*comprimento)
Fimalgoritmo