Algoritmo "Volumedelatadeoleo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Recebe a altura e o raio de um cilindro e calcula seu volume.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
altura, raio:real
Inicio
Escreval("Digite a altura do cilíndro: ")
Leia(altura)
Escreval("Digite o raio do cilíndro: ")
Leia(raio)
Escreval("O volume do cilíndro é de:",pi*raio^2*altura)
Fimalgoritmo