Algoritmo "Fahreinheit para Celsius"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar a temperatura em Fahreinheit e converter para Celsius
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
tempfahr:real
Inicio
Escreval("Digite a temperatura em graus Fahreinheit: ")
Leia(tempfahr)
Escreval("A temperatura em graus Celsius é de:", (tempfahr-32)*(5/9))
Fimalgoritmo