Algoritmo "Quadradodadiferença"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Ler dois valores inteiros e calcular o quadrado da diferença deles.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
A,B:inteiro
Inicio
Escreval("Escreva o primeiro termo: ")
Leia(A)
Escreval("Escreva o segundo termo: ")
Leia(B)
Escreval("O quadrado da diferença do primeiro e do segundo termo é :", A^2-2*A*B+B^2)
Fimalgoritmo