Algoritmo "Conversãodemoeda2"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa lê a cotação do dolar para o real, quantos reais o usuário tem e converte para dolar.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
cotacao,reais:real
Inicio
Escreval("Digite a cotação do dolar para o real atualmente: ")
Leia(cotacao)
Escreval("Digite quantos reais você possuí: ")
Leia(reais)
Escreval("Com essa quantidade de reais você consegue:",reais/cotacao," dolares, quem converte não se diverte :c")
Fimalgoritmo