Algoritmo "quadradodassomas"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa lê três valores diferentes e realiza o quadrado da soma deles.
// Autor(a) : Vinicius Correa
// Data atual  : 20/03/2024
Var
A,B,C:real
Inicio
Escreval("Digite o primeiro valor: ")
Leia(A)
Escreval("Digite o segundo valor: ")
Leia(B)
Escreval("Digite o terceiro valor: ")
Leia(C)
Escreval("O quadrado da soma de todos os valores é:",(A+B+C)^2)
Fimalgoritmo