Algoritmo "ímparoupar"
// Disciplina   : [Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : Elaborar um programa que efetue a leitura de um número inteiro e apresentar uma mensagem
// informando se o número é par ou ímpar.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 07/04/2024
Var
   valor:inteiro
Inicio
   Escreval("Digite o valor: ")
   leia(valor)
   se valor%2=0 entao
      Escreval("O valor é par")
   senao
      Escreval("O valor é ímpar")
   fimse
Fimalgoritmo