Algoritmo "valorpermitido"
// Disciplina   : [Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : Recebe um valor e exibe se ele for menor ou igual a 3.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 04/04/2024
Var
   multi,cont:inteiro
Inicio
   cont<-1
   Escreval("Digite o numero a ser multiplicado")
   Leia(multi)
   enquanto cont<=10 faca
      Escreval(multi," X",cont," =",multi*cont)
      cont<-cont+1
   fimenquanto
Fimalgoritmo