Algoritmo "impares0ate20"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar todos os valores numéricos inteiros ímpares situados na faixa de 0 a 20. Para verificar
// se o número é ímpar, efetuar dentro da malha a verificação lógica desta condição com a instrução
// se, perguntando se o número é ímpar; sendo, mostre-o; não sendo, passe para o próximo passo.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 13/04/2024
Var
   contador:inteiro
Inicio
Escreval("Todos os números impares inteiros na faixa de 0 até 20 são: ")
   enquanto contador <= 20 faca
      se contador%2 = 1 entao
         Escreval(contador)
      fimse
      contador<-contador+1
   fimenquanto
FimAlgoritmo