Algoritmo "quadrados15a200"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 13/04/2024
Var
   contador:inteiro
Inicio
   contador<-15
   repita
      Escreval(contador," elevado por 2 é",contador*contador)
      contador<-contador+1
   ate (contador = 201)
FimAlgoritmo