Algoritmo "quadrados 15 a 200"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 21/04/2024
Var
   i:inteiro
Inicio
   para i de 15 ate 200 passo 1 faca
   Escreval(i," ao quadrado é igual a:",i^2)
   fimpara
FimAlgoritmo