Algoritmo "tabuada"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 21/04/2024
Var
   i,valor:inteiro
Inicio
Escreval("Digite o valor para ver a tabuada.")
leia(valor)
   para i de 1 ate 10 passo 1 faca
   Escreval(valor," X",i," =",valor*i)
   fimpara
FimAlgoritmo