Algoritmo "soma1até100"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 21/04/2024
Var
   i,soma:inteiro
Inicio
   para i de 1 ate 100 passo 1 faca
      soma<-soma+i
   fimpara
   Escreval("A soma de 1 até 100 é:",soma)
FimAlgoritmo