Algoritmo "numerosimpares"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar todos os valores numéricos inteiros ímpares situados na faixa de 0 a 20.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 21/04/2024
Var
   i:inteiro
Inicio
Escreval("Todos os valores impares no intervalo 0 até 20 são: ")
   para i de 0 ate 20 passo 1 faca
      se i%2 <> 0 entao
         Escreval(i)
      fimse
   fimpara
FimAlgoritmo