Algoritmo "divisivelpor4"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Apresentar todos os números divisíveis por 4 que sejam menores que 200.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 21/04/2024
Var
   i:inteiro
Inicio
Escreval("Todos os valores divisiveis por 4 no intervalo 1 até 200 são: ")
   para i de 1 ate 200 passo 1 faca
      se i%4 = 0 entao
         Escreval(i)
      fimse
   fimpara
FimAlgoritmo