Algoritmo "CeliusparaFahrenheit"
// Disciplina   : [Logica de Programacao em java script]
// Professor   : Jailson Costa
// Descrição   : Elaborar um programa que apresente os valores de conversão de graus Celsius em Fahrenheit, de
// 10 em 10 graus, iniciando a contagem em 10 graus Celsius e finalizando em 100 graus Celsius.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 21/04/2024
Var
   celsius:inteiro
   fahr:real
Inicio
   para celsius de 10 ate 100 passo 10 faca
   fahr<-(9*celsius+160)/5
   Escreval(celsius,"ºC =",fahr," ºF")
   fimpara
FimAlgoritmo