Algoritmo "diasdasemanasc"
// Disciplina   : [Linguagem e Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa recebe um numero de 1 a 7 e exibe o seu representante na semana utilizando select case.
// Autor(a)    : Vinicius Correa
// Data atual  : 27/03/2024
Var
   dia:inteiro
Inicio
   Escreval("Digite o número do dia da semana: ")
   Leia(dia)
   escolha dia
   caso 1
      Escreval("Domingo")
   caso 2
      Escreval("Segunda-feira")
   caso 3
      Escreval("Terça-feira")
   caso 4
      Escreval("Quarta-feira")
   caso 5
      Escreval("Quinta-feira")
   caso 6
      Escreval("Sexta-feira")
   caso 7
      Escreval("Sábado")
   outrocaso
      Escreval("Não há dia correspondente")
   fimescolha
Fimalgoritmo