Algoritmo "maiorque10"
// Disciplina   : [Linguagem e Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa le um valor e exibe se ele e ou nao maior que 10.
// Autor(a)    : Vinicius Correa
// Data atual  : 21/03/2024
Var
   valor:real
Inicio
   Escreval("Digite um valor a ser processado: ")
   Leia(valor)
   se (valor > 10) entao
      Escreval("O valor e maior que 10!")
   senao
      Escreval("O valor nao e maior que 10!")
   fimse
Fimalgoritmo