Algoritmo "positivoounegativo"
// Disciplina   : [Linguagem e Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa recebe um valor e exibe se ele e positivo ou nao
// Autor(a)    : Vinicius Correa
// Data atual  : 21/03/2024
Var
   valor:real
Inicio
   Escreval("Digite um valor e veja se ele e positivo ou negativo: ")
   Leia(valor)
   se (valor < 0) entao
      Escreval("O valor digitado e negativo!")
   senao
      Escreval("O valor digitado e positivo!")
   fimse
Fimalgoritmo