Algoritmo "Area do losângulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar as diagonais do losângulo e calcular sua area.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
diagonal1:real
diagonal2:real
Inicio
Escreval("Digite a primeira diagonal do losângulo: ")
Leia(diagonal1)
Escreval("Digite a segunda diagonal do losângulo: ")
Leia(diagonal2)
Escreval("A área do losângulo é de:", (diagonal1*diagonal2)/2)
Fimalgoritmo