Algoritmo "maiornumero"
// Disciplina   : [Linguagem e Lógica de Programação em JavaScript]
// Professor   : Jailson Costa
// Descrição   : O programa recebe dois valores e exibe o maior deles
// Autor(a)    : Vinicius Correa
// Data atual  : 21/03/2024
Var
   numero1, numero2:inteiro
Inicio
Escreval("Digite o primeiro numero: ")
Leia(numero1)
Escreval("Digite o segundo numero (diferente do primeiro): ")
Leia(numero2)
se (numero1 > numero2) entao
Escreval("O primeiro numero:",numero1," e o maior")
senao
Escreval("O segundo numero:",numero2," e o maior")
fimse
Fimalgoritmo