Algoritmo "Calculador de média ponderada"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Ler três notas e calcular sua média baseada em seus pesos dados previamente.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
nota1:real
nota2:real
nota3:real
Inicio
Escreval("Digite a primeira nota do aluno: ")
Leia(nota1)
Escreval("Digite a segunda nota do aluno: ")
Leia(nota2)
Escreval("Digite a terceira nota do aluno: ")
Leia(nota3)
Escreval("A média final do aluno é de:",((nota1*2)+(nota2*3)+(nota3*5))/10)
fimalgoritmo