Algoritmo "Conversor de graus Fahrenheit para Celsius"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Ler uma temperatura em Fahrenheit e converter para graus Celsius.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
fahr:real
Inicio
Escreval("Escreva a temperatura em Fahrenheit: ")
Leia(fahr)
Escreval("O valor em graus Celsius é de:",((fahr-32)/9)*5)
Fimalgoritmo