Algoritmo "Area do triângulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar a base e altura de um triângulo e calcular sua area.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 20/03/2024
Var
base:real
altura:real
Inicio
Escreval("Digite a base do triângulo: ")
Leia(base)
Escreval("Digite a altura do triângulo: ")
Leia(altura)
Escreval("A área do triângulo é de:", (base*altura)/2)
Fimalgoritmo