Algoritmo "Dias vividos"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Algoritmo que recebe os anos, meses e dias vividos e converte apenas para os dias totais.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 18/03/2024
Var
anos, mes, dia:inteiro
Inicio
Escreval("Quantos anos você tem de idade?")
Leia(anos)
Escreval("Quantos meses se passaram desde o seu último aniversário?")
Leia(mes)
Escreval("Quantos dias se passaram desde o seu último mêsversário?")
Leia(dia)
Escreval("Você viveu",anos*365+mes*30+dia," dias no total")
Fimalgoritmo