Algoritmo "Area do retangulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar a base e a altura de um retângulo e calcular sua area.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 18/03/2024
Var
base:real
altura:real
Inicio
Escreva("Digite a base do retangulo: ")
Leia(base)
Escreva("Digite a altura do retangulo: ")
Leia (altura)
Escreva("A área do retângulo é de : ", base*altura)
Fimalgoritmo