Algoritmo "MULTIPLICACAO"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar dois valores e exibir o resultado da multiplicacao.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 18/03/2024
Var
numero1:inteiro
numero2:inteiro
multiplicacao:inteiro
Inicio
Escreva("Digite um numero: ")
Leia(numero1)
Escreva("Digite um numero: ")
Leia(numero2)
multiplicacao<-numero1 * numero2
Escreva("O resultado da Multiplicacao é:", multiplicacao)

Fimalgoritmo