Algoritmo "Soma"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar um valor e exibir o seu sucessor.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 18/03/2024
Var
numero1:inteiro
sucessor:inteiro
Inicio
Escreva("Digite um numero inteiro: ")
Leia(numero1)
sucessor<-numero1+1
Escreva("O seu sucessor é:", sucessor)

Fimalgoritmo