Algoritmo "Subtracao"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicitar dois valores e exibir o resultado da subtração.
// Autor(a)    : Vinicius Correa Carvalho
// Data atual  : 18/03/2024
Var
numero1:inteiro
numero2:inteiro
subtracao:inteiro
Inicio
Escreva("Digite um numero: ")
Leia(numero1)
Escreva("Digite um numero: ")
Leia(numero2)
subtracao<-numero1-numero2
Escreva("O resultado da Subtracao é:", subtracao)

Fimalgoritmo